ips:
  - 192.168.0.102 # 0
  - 192.168.0.103 # 1
  - 192.168.0.104 # 2
  - 192.168.0.105 # 3
channel: 36
bandwidth: 80
mac_address: dc:a6:32:b7:64:1b
interface: wlan0
custom_cmd: 500
cmd_buffer_len: 34
coremask: 1
nssmask: 1

room_id: 12
wall_structure: #x0, y0 are the walls that are on along x axis and y axis
    x0: blocks
    y0: geves
    x1: blocks
    y1: blocks
description: room 12 - with humans
locations:
  camera:
    x: 0.25
    y: 0.07
    z: 1.83
  "192.168.0.100":
    x: 1.12
    y: 0.48
    z: 0.45
  "192.168.0.102":
    x: 3.7
    y: 2.7
    z: 0.73
  "192.168.0.103":
    x: 1.32
    y: 0.34
    z: 0.45
  "192.168.0.104":
    x: 5.62
    y: 0.3
    z: 0
  "192.168.0.105":
    x: 3.2
    y: -0.51
    z: 0.45
  qr102:
    x: 2.23
    y: 0.95
    z: 0
  qr103:
    x: 2.9
    y: 1.56
    z: 0
  qr104:
    x: 3.22
    y: 0.88
    z: 0
  room:
    x: 6.1
    y: 3.19
    z: 3