ips:
  - 192.168.0.102 # 0
  - 192.168.0.103 # 1
  - 192.168.0.104 # 2
  - 192.168.0.105 # 3
channel: 36
bandwidth: 80
mac_address: dc:a6:32:b7:64:1b
interface: wlan0
custom_cmd: 500
cmd_buffer_len: 34
coremask: 1
nssmask: 1

room_id: 4
wall_structure: #x0, y0 are the walls that are on along x axis and y axis
    x0: beton + geves
    y0: beton + geves
    x1: beton + geves
    y1: beton + geves
description: Room 4 (interview room) - human with movement. 2021/09/13 00:00
locations:
  camera:
    x: 2.1
    y: 4.05
    z: 1.89
  "192.168.0.100": # AP
    x: 0.94
    y: 1.84
    z: 0.75
  "192.168.0.102":
    x: 2.25
    y: 0.37
    z: 0.49
  "192.168.0.103":
    x: 0.94
    y: 1.34
    z: 1
  "192.168.0.104":
    x: 2.05
    y: 3.29
    z: 0.28
  "192.168.0.105":
    x: -0.89
    y: 0.33
    z: 0.49
  qr102:
    x: 1.97
    y: 1.49
    z: 0
  qr103:
    x: 0.98
    y: 2.34
    z: 0.73
  qr104:
    x: 0.4
    y: 2.7
    z: 0
  room:
    x: 2.52
    y: 4.11
    z: 2.45
