ips:
  - 192.168.0.102 # 0
  - 192.168.0.103 # 1
  - 192.168.0.104 # 2
  - 192.168.0.105 # 3
channel: 36
bandwidth: 80
mac_address: dc:a6:32:b7:64:1b
interface: wlan0
custom_cmd: 500
cmd_buffer_len: 34
coremask: 1
nssmask: 1

room_id: 3
wall_structure: #x0, y0 are the walls that are on along x axis and y axis
    x0: geves
    y0: geves
    x1: geves
    y1: geves + beton
description: Room 3 (Reish) - human with movement. 2021/09/13 22:00
locations:
  camera:
    x: 5.2
    y: 2.82
    z: 2.16
  "192.168.0.100": # AP
    x: 4
    y: 2.36
    z: 0.73
  "192.168.0.102":
    x: 1.45
    y: 1.69
    z: 0.72
  "192.168.0.103":
    x: 3.5
    y: 2.36
    z: 0.73
  "192.168.0.104":
    x: 4.42
    y: 0.34
    z: 0.47
  "192.168.0.105":
    x: -0.61
    y: -1.34
    z: 0.47
  qr102:
    x: 3.4
    y: 0.88
    z: 0
  qr103:
    x: 2.45
    y: 1.59
    z: 0
  qr104:
    x: 2.58
    y: 0.79
    z: 0
  room:
    x: 6.36
    y: 2.98
    z: 3.05
