ips:
  - 192.168.0.102 # 0
  - 192.168.0.103 # 1
  - 192.168.0.104 # 2
  - 192.168.0.105 # 3
channel: 36
bandwidth: 80
mac_address: dc:a6:32:b7:64:1b
interface: wlan0
custom_cmd: 500
cmd_buffer_len: 34
coremask: 1
nssmask: 1

room_id: 0
wall_structure: #x0, y0 are the walls that are on along x axis and y axis
    x0: geves
    y0: geves
    x1: geves
    y1: geves
description: Room 0 - with people. 2021/09/12 19:57
locations:
  camera:
    x: 3.02
    y: 5.01
    z: 1.9
  "192.168.0.100": # AP
    x: 1.61
    y: 4.82
    z: 0.73
  "192.168.0.102":
    x: 2.94
    y: 2.77
    z: 0.73
  "192.168.0.103":
    x: 1.38
    y: 4.83
    z: 0.73
  "192.168.0.104":
    x: 0.4
    y: 2.9
    z: 0.45
  "192.168.0.105":
    x: 0.87
    y: -0.40
    z: 0.65
  qr102:
    x: 0.95
    y: 2.74
    z: 0
  qr103:
    x: 2.25
    y: 2.82
    z: 0
  qr104:
    x: 2.06
    y: 1.91
    z: 0
  room:
    x: 3.59
    y: 5.37
    z: 2.38
